# Schema for the configuration files of the Media Facebook Post module.

media_facebook_post.settings:
  type: config_object
  mapping:
    authentication:
      type: mapping
      mapping:
        app_id:
          type: string
        app_secret:
          type: string
